name: PatternJournal Build 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: docker-compose build
      run: docker-compose build --no-cache

    - name: docker-compose up
      # run: docker-compose up --detach
      run: docker-compose up --abort-on-container-exit

    - name: wait for postgres
      run: sleep 300 

    - name: docker debut
      run: docker ps

    - name: create test database
      run: docker exec --user postgres pj-db createdb pj_test

    - name: migrate test database
      run: docker run --network container:web pj-web npm run migrate
      env:
        NODE_ENV: test

    - name: run tests
      run: docker run --network container:web npm run test
      env:
        SESSION_SECRET: yabbadabbadoo
        G_AUTH_CLIENT_ID: XXCLIENTIDXX 
        G_AUTH_CLIENT_SECRET: XXCLIENTSECRETXX
        G_AUTH_CALLBACK: http://example.com
    # TODO: uncomment me
    # - name: Code Coverage
    #   uses: codecov/codecov-action@v1.0.2
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
