name: PatternJournal Build 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: docker-compose up
      run: docker-compose up --detach

    - name: create test database
      run: docker-compose exec --user postgres db createdb pj_test
      env:
        COMPOSE_INTERACTIVE_NO_CLI: true
        NODE_ENV: test

    - name: migrate test database
      run: docker-compose run web npm run migrate
      env:
        NODE_ENV: test

    - name: run tests
      run: docker-compose run web npm run test
      env:
        SESSION_SECRET: yabbadabbadoo
        G_AUTH_CLIENT_ID: XXCLIENTIDXX 
        G_AUTH_CLIENT_SECRET: XXCLIENTSECRETXX
        G_AUTH_CALLBACK: http://example.com

    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
