name: PatternJournal Build 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: npm install, build, and test
      run: |
        env 
        npm ci
        npm run build --if-present
        npm test
      env:
        SESSION_SECRET: yabbadabbadoo
        G_AUTH_CLIENT_ID: XXCLIENTIDXX 
        G_AUTH_CLIENT_SECRET: XXCLIENTSECRETXX
        G_AUTH_CALLBACK: http://example.com
